name: start
author: Yehor Lvivski <lvivski@gmail.com>
version: 0.2.4
homepage: http://github.com/lvivski/start
description: Sinatra inspired Web framework
environment:
  sdk: '>=0.8.10+6 <2.0.0'
dependencies:
  logging: any
  http_server: any

dev_dependencies:
  unittest: '>=0.2.7'
  browser: any
