name: start
author: Yehor Lvivski <lvivski@gmail.com>
version: 0.2.7
homepage: http://github.com/lvivski/start
description: Sinatra inspired Web framework
environment:
  sdk: '<2.0.0'
dependencies:
  logging: any
  http_server: any
  mime: any

dev_dependencies:
  test: any
  browser: any
  mockito: any
